# Generated by Django 4.0.5 on 2023-01-11 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkedbugs',
            old_name='cover',
            new_name='photo',
        ),
    ]
